name: FASTCOMPOSER-Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstrap
        run: |
          npm install
      - name: Begin Test
        run: |
          npm run ci:test
        env:
          CI: true
